### ISSUE TITLE
Incorrect folder moved on line 53

### ISSUE THREAD

**Issue by ghost** [tamimhasan404/Open-Source-Nuclei-Templates-Downloader#1]
Hi,
I just tried out your script, on line 53, you try to move "nuclei-templates" to nuclei_templates-4 but the file you downloaded is nuclei_templates.

It should be:
mv nuclei_templates nuclei_templates-4

Thanks :)

**Comment by tamimhasan404** [comment]
Thank you for showing me this issue. This issue is solved now can you please confirm?

**Comment by ghost** [comment]
Working fine now :) thanks
